name: Sonar Cloud code scan

on:
  push:
    branches: [ master ]

jobs:
  sonarcloud:
    name: Analyse SonarCloud
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch # On se place sur la branch master
      uses: actions/checkout@v2
    
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=baralga -Dsonar.organization=baralga -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}