name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Integration
    runs-on: ubuntu-latest
    steps:

      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Maven Clean & Package
        run: mvn -B clean package --file pom.xml

      - name: Recherche du .jar
        run: cd target/
        run: ls