name: Sonar Cloud code scan

on:
  push:
    branches: [ master ]

jobs:
  sonarcloud:
    name: Analyse SonarCloud
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch # On se place sur la branch master
      uses: actions/checkout@v2
    
    - name: SonarCloud Scan
      run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=Projet-Spring-Boot_Integration -Dsonar.organization=projet-spring-boot-integration -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}